version: 2.1

rok8s-scripts: fairwinds/rok8s-scripts@11

references:
  setup_environment: &setup_environment
    run:
      name: Setup Environment
      command: |
        echo 'export CI_SHA1=$CIRCLE_SHA1' >> ${BASH_ENV}
        echo 'Install AWS CLI'
        pip install awscli
        echo 'Install needed packages'
        apk --update add bash jq
  kind_configuration: &kind_configuration
    pre_script: scripts/e2e-pre.sh
    script: scripts/e2e.sh
    kind_version: 0.7.0
    command_runner_image: quay.io/reactiveops/ci-images:v11-stretch
    requires:
      - lint-scripts
      - lint-charts
    filters:
      branches:
        ignore: master

jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine:v0.7.0
    steps:
      - checkout
      - run:
          name: lint
          command: |
            for script in $(ls scripts/*.sh); do
                shellcheck -x $script
            done
      - run:
          name: lint-pre-scripts
          command: |
            for script in $(find incubator stable -type f -name pre-test-script.sh); do
                shellcheck -x $script
            done
  lint-charts:
    docker:
      - image: quay.io/helmpack/chart-testing:v3.0.0-beta.1
    steps:
      - checkout
      - *setup_environment
      - run:
          name: lint
          command: |
            git remote add ro https://github.com/fairwindsops/charts
            git fetch ro master
            ct lint --config scripts/ct.yaml  --chart-yaml-schema scripts/schema.yaml
  sync:
    docker:
      - image: quay.io/helmpack/chart-testing:v3.0.0-beta.1
    steps:
      - checkout
      - *setup_environment
      - run:
          name: sync
          command: scripts/repo-sync.sh
      - run:
          name: sync-fw
          command: scripts/repo-sync-fw.sh
workflows:
  version: 2
  test-and-sync:
    jobs:
      - lint-scripts
      - lint-charts
      - rok8s-new/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.14.10"
          kind_node_image: "kindest/node:v1.14.10@sha256:81ae5a3237c779efc4dda43cc81c696f88a194abcc4f8fa34f86cf674aa14977"
          <<: *kind_configuration
      - rok8s-new/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.15.7"
          kind_node_image: "kindest/node:v1.15.7@sha256:e2df133f80ef633c53c0200114fce2ed5e1f6947477dbc83261a6a921169488d"
          <<: *kind_configuration
      - rok8s-new/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.16.4"
          kind_node_image: "kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55"
          <<: *kind_configuration
      - rok8s-new/kubernetes_e2e_tests:
          name: "End-To-End Kubernetes 1.17.0"
          kind_node_image: "kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62"
          <<: *kind_configuration
      - sync:
          requires:
            - lint-scripts
            - lint-charts
          filters:
            branches:
              only:
                - master
